apps/planteamientos/urls.py
from django.urls import path
from . import views

app_name = 'planteamientos'
urlpatterns = [

    path('mostrar/<int:todos>', views.planteamiento, name='planteamiento'),
    path('inbox/<int:planteamiento_id>/', views.inbox, name='inbox'),
    path('crear/', views.crear_planteamiento, name='crear_planteamiento'),
    path('notificaciones/', views.notificaciones, name='notificaciones'),
    path('editar/<id_planteamiento>/', views.editar_planteamiento, name='editar'),
    path("import/xlsx/", views.PlanteamientosImportXLSXService.as_view(),
         name="xlsx"),
    path("evaluacion/<int:planteamiento_id>/<int:aprobado>", views.PlanteamientosAprobar.as_view(), name="evaluar_planteamiento")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.mixin import login, errors
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import cache_control
from django.conf import settings

handler404 = errors.handler_404
handler500 = errors.handler_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('planteamientos/', include('apps.planteamientos.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('unidades/', include('apps.respuestas.urls')),
    path('unidades/', include('apps.unidades.urls')),
    path('', login.login, name='login'),
    path('logout', login.logout, name='logout'),
    path('olvidado/', login.olvidar_contrasegna, name='olvidar')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

apps/planteamientos/models.py
from django.db import models
from apps.unidades.models import UnidadOrganizativa, SeccionSindical
from django.utils import timezone
from datetime import datetime, timedelta


def dias_habiles(date: datetime, cont=0):
    if cont == 10:
        return date
    else:
        return dias_habiles(date + timedelta(1), cont + 1 if date.isoweekday() not in [6, 7] else cont)


class Procesos(models.Model):
    proceso = models.CharField(max_length=50)

    def __str__(self):
        return self.proceso


class Planteamiento(models.Model):
    """
    model Planteamientos; \n
     your instance gets: \n
        * titulo -- titulo como referencia \n
        * descripcion -- contendo del planteamiento \n
        * estado -- estado del planteamiento, por defecto "Nuevo" \n
        * fecha -- fecha de creacion \n
        * secretario -- secretario que encomendo el planteamiento \n
        * seccion_sindical -- seccion sindical al que pertenece el secretario
        * unidad -- unidad que recibe el planteamiento
    """

    # estados de los

    ESTANCADO = 'Estancado'
    NUEVO = 'Nuevo'
    PENDIENTE = 'Pendiente'
    SOLUCIONADO = 'Solucionado'

    Choices = (
        (ESTANCADO, 'Estancado'),
        (NUEVO, 'Nuevo'),
        (PENDIENTE, 'Pendiente'),
        (SOLUCIONADO, 'Solucionado')
    )

    # clasificacion de los planteamientos
    Choices2 = (
        ('Territorial', 'Territorial'),
        ('Nacional', 'Nacional')
    )

    titulo = models.CharField(max_length=24)
    descripcion = models.TextField()
    estado = models.CharField(max_length=20, choices=Choices, default=ESTANCADO)
    fecha = models.DateField(default=timezone.now)
    modificado = models.DateField(default=timezone.now)
    fecha_vencida = models.DateField()
    secretario = models.CharField(max_length=60)
    seccion_sindical = models.ForeignKey(SeccionSindical, on_delete=models.SET_NULL, null=True)
    unidad = models.ForeignKey(UnidadOrganizativa, on_delete=models.SET_NULL, null=True)
    clasificacion = models.CharField(max_length=12, choices=Choices2, default='Territorial')
    procesos = models.ForeignKey(Procesos, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.titulo}, {self.unidad}, {self.seccion_sindical}, {self.estado}, {self.fecha} "

    def abreviar(self):
        breve = self.descripcion[:100]
        return breve

    def get_unidad(self):
        return self.unidad.nombre

    def tiene_respuestas(self):
        from apps.respuestas.models import HistorialRespuesta
        return any(self.id is i.planteamiento_id for i in HistorialRespuesta.objects.all())

apps/planteamientos/views.py
from django.db.models import Q, QuerySet
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from apps.mixin.login import secretario
from .models import Planteamiento, Procesos
from apps.mixin.utils import UsuarioLogin, Html, sum_days
from apps.mixin.forms import FormPlanteamiento
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from apps.respuestas.models import HistorialRespuesta
from apps.notification.notification import Notification
from apps.notification.emails import send_mail
from django.contrib import messages
from apps.unidades.models import UnidadOrganizativa, SeccionSindical
from django.views import View
from xlsxwriter import Workbook
import  io
from django.http import HttpResponse
import datetime
from dataclasses import dataclass
from django.template.loader import get_template

class ImportXLXSService:

    @classmethod
    def write_header(cls, workbook, worksheet):
        header = ["Fecha de Creación", "Fecha de Vencimiento",
                  "Clasificación", "Estado", "Proceso", "Unidad", "Sección Sindical",
                  "Secretario", "Título", "Descripción", "Respuesta"]

        header_format = workbook.add_format({"bold": True})
        header_format.set_bg_color("00b0f0")
        worksheet.write_row("A1", header, header_format)
        worksheet.set_column(0, 7, 20)
        worksheet.set_column(8, 11, 30)

        return worksheet

    @classmethod
    def execute(cls, planteamientos):
        file = io.BytesIO()

        workbook = Workbook(file)
        worksheet = workbook.add_worksheet()

        cls.write_header(workbook, worksheet)

        row = 2
        for planteamiento in planteamientos:
            worksheet.write(f"A{row}", planteamiento.fecha.isoformat())

            worksheet.write(f"B{row}", planteamiento.fecha_vencida.isoformat())

            worksheet.write(f"C{row}", planteamiento.clasificacion)

            worksheet.write(f"D{row}", planteamiento.estado)

            worksheet.write(f"E{row}", planteamiento.procesos.proceso)

            worksheet.write(f"F{row}", planteamiento.unidad
                            and planteamiento.unidad.nombre or "")

            worksheet.write(f"G{row}",
                            planteamiento.seccion_sindical
                            and planteamiento.seccion_sindical.nombre or "")

            worksheet.write(f"H{row}", planteamiento.secretario)
            worksheet.write(f"I{row}", planteamiento.titulo)
            worksheet.write(f"J{row}", planteamiento.descripcion)

            respuesta = HistorialRespuesta.objects.filter(
                planteamiento_id=planteamiento.id)\
                .values("descripcion").last()

            worksheet.write(f"J{row}", respuesta and
                            respuesta.get("descripcion", ""))

            row += 1

        workbook.set_properties({
            'title': 'Planteamientos',
            'subject': 'Planteamientos',
            'author': 'user',
            'manager': 'manager',
            'company': 'ETECSA S.A',
            'category': 'Example spreadsheets',
            'keywords': 'Sample, Example, Properties',
            'created': datetime.date(2018, 1, 1)})

        workbook.close()
        file.seek(0)

        return file


class PlanteamientosImportXLSXService(View):

    def get(self, request):

        planteamientos = Planteamiento.objects.all()
        file = ImportXLXSService.execute(planteamientos)

        filename = "planteamientos.xlsx"

        response = HttpResponse(
            file,
            content_type="application/vnd.openxmlformats-"
                         "officedocument.spreadsheetml.sheet"
        )

        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response

@login_required(login_url="login")
def planteamiento(request, todos) -> HttpResponse:
    usuario = UsuarioLogin(request)
    planteamientos = usuario.plant()
    unidades = UnidadOrganizativa.objects.all()
    secciones = SeccionSindical.objects.all()
    procesos = Procesos.objects.all()
    fecha_hoy = timezone.now().date()

    if todos == 1:
        planteamientos = Planteamiento.objects.all()
    if todos == 2:
        usuario = UsuarioLogin(request)
        planteamientos = usuario.plant(estado=None)

    if request.method == 'POST':
        fields = ['titulo', 'estado', 'seccion_sindical_id',
                  'unidad_id', 'clasificacion', 'procesos_id',
                  'fecha', 'fecha_vencida']

        fields = [{i: request.POST[i]} for i in request.POST
                  if request.POST[i] not in ('No Especificado', '') and i in fields]
        for field in fields:
            resp = planteamientos.filter(**field)
            planteamientos = resp

    return render(request, 'planteamientos/planteamientos.html', locals())


@login_required(login_url="login")
def inbox(request, planteamiento_id, respuesta_a_editar=" ", *, show='hidden') -> HttpResponse:
    procesos = Procesos.objects.all()
    usuario = UsuarioLogin(request)
    planteamientos = usuario.plant(limit=10)
    notify = Notification(request)
    notification = notify.get_list_notify()

    if planteamiento_id != 0:
        mostrar = get_object_or_404(Planteamiento, id=planteamiento_id)
        respuestas = HistorialRespuesta.objects.filter(Q(planteamiento_id=mostrar.id))

        for i in respuestas:
            try:
                if i.planteamiento.seccion_sindical.secretario.id == request.user.id:
                    i.leido = True
                    i.save()

            except AttributeError:
                pass
    else:
        mostrar = usuario.ultimo_planteamiento()
        respuestas = usuario.respuestas()

    form = FormPlanteamiento(initial={'unidad': mostrar.unidad,
                                      'procesos': mostrar.procesos} if mostrar is not None else None)
    if mostrar is not None:
        if mostrar.estado != 'Solucionado':
            atraso = (mostrar.fecha_vencida - timezone.now().date()).days
            if 0 < atraso < 5:
                msj = 'Este planteamiento le quedan {} días para que ' \
                      'culmine su plazo de respuesta'.format(atraso)
                messages.warning(request, msj, 'ADVERTENCIA !!')

                send_mail("Gestión Planteamiento", msj, mostrar.unidad.responsable.email)

            elif atraso <= 0 and not mostrar.tiene_respuestas():
                historial = HistorialRespuesta()
                respuesta = 'Se incumple el tiempo de respuesta del planteamiento por %s ' \
                            % ('el Área Rectora Nacional' if mostrar.clasificacion == 'Nacional'
                               else 'la Actividad Rectora Territorial')
                historial.planteamiento_id = mostrar.id
                historial.descripcion = respuesta
                historial.fecha = timezone.now().date()
                historial.autor = 'Gestión Planteamiento'
                mostrar.estado = 'Pendiente'
                mostrar.save()
                historial.save()

    if respuestas is not None: respuestas = respuestas.order_by('-id')
    if request.method == 'GET':
        if 'hidden' in request.GET.values():
            show = 'show'

    if request.method == "POST":
        if 'clasificar' in request.POST:
            mostrar.clasificacion = request.POST['clasificacion']
            mostrar.save()
        elif 'proceso' in request.POST:
            mostrar.procesos_id = request.POST['procesos']
            mostrar.save()
        else:
            mostrar.unidad_id = request.POST['unidad']
            mostrar.fecha = timezone.now().date()
            mostrar.fecha_vencida = sum_days(timezone.now().date(), 10)
            mostrar.save()

            if mostrar.estado != Planteamiento.ESTANCADO:
                # enviar correo
                mensaje = 'Hola {}!! \r' \
                          'Se le ha reenviado por el administrador {}' \
                          ' un Planteamiento de la sección sindical {}, ' \
                          'Tiene plazo de 10 días hábiles para darle respuesta.' \
                    .format(mostrar.unidad.responsable.first_name, request.user.first_name,
                            mostrar.seccion_sindical.nombre)
                send_mail('Gestión Planteamiento', mensaje, mostrar.unidad.responsable.email)

            # notificar
            mensaje2 = 'Se ha reenviado el planteamiento de la sección {} para la unidad {}' \
                .format(mostrar.seccion_sindical.nombre, mostrar.unidad)
            messages.success(request, mensaje2, 'ÉXITOS !')

    Notification.del_notify(request, planteamiento_id)

    return render(request, 'planteamientos/inbox.html', locals())


@user_passes_test(secretario, login_url='login')
@login_required(login_url="login")
def crear_planteamiento(request) -> HttpResponse:
    form = FormPlanteamiento()

    if request.method == "POST":
        datos = {key: request.POST[key] for key in request.POST}
        descripcion = Html.get_text(datos['descripcion'])
        datos['descripcion'] = descripcion
        datos['secretario'] = request.user.first_name
        datos['seccion_sindical'] = UsuarioLogin.relacion(request, seccion=True)
        datos["estado"] = Planteamiento.ESTANCADO
        datos["fecha"] = timezone.now()
        datos["modificado"] = timezone.now()
        datos["fecha_vencida"] = sum_days(timezone.now(), 10)
        form = FormPlanteamiento(data=datos)
        if form.is_valid():
            form.save()
            # notificar
            mensaje = 'Se ha adicionado satisfactoriamente el planteamiento {}'.format(datos['titulo'])
            messages.success(request, mensaje, 'ÉXITO ! ')
            return redirect('planteamientos:planteamiento', 0)
        else:
            # notificar

templates/planteamientos/notification.html
{% extends 'base.html' %}

{% block body %}

    <div class="right_col" role="main" style="min-height: 5167px;">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Notificaciones</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-secondary" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>


            <div class="col-md-12 col-sm-12  ">
              <div class="x_panel">
                <div class="x_title">
                  <h2> <small>Sessions</small></h2>

                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <ul class="list-unstyled timeline">
                  {% for notificacion in lista_notificaciones %}
                    <li>
                      <div class="block">
                        <div class="tags">
                          <a href="{% url 'planteamientos:inbox' notificacion.id %}" class="tag">
                              {% if notify.tiene_seccion %}
                            <span> Respondido </span>
                              {% endif %}
                            {% if notify.tiene_unidad %}
                                <span> Corregir </span>
                            {% endif %}
                          {% if user.is_staff %}
                              <span> Evaluar </span>
                            {% endif %}
                          </a>
                        </div>
                        <div class="block_content">
                          <h2 class="title">
                                          {{ notificacion.titulo }}
                                      </h2>
                          <div class="byline">
                            <span>{{ notificacion.fecha }}</span> por {{ notificacion.seccion_sindical }}
                          </div>
                          <p class="excerpt">{{ notificacion.abreviar }}...
                          </p>
                        </div>
                      </div>
                    </li>
                  {% endfor %}


                  </ul>

                </div>
              </div>
            </div>
          </div>
    </div>


{% endblock %}

templates/planteamientos/planteamientos.html
{% extends 'base.html' %}
{% load static %}
{% load planteamientos_tags %}

{% block body %}

    <div class="right_col" role="main" style="min-height: 5282px;">
          <div class="">
              <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                  <div class="x_title d-flex">
                    <h2>Planteamientos<small><a href="{% url 'planteamientos:planteamiento' 1 %}">Ver todos</a></small></h2>
                  <div class="ml-auto">
                    <a type="button" class="btn btn-success btn-sm"  href="{% url "planteamientos:xlsx" %}">Excel</a>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".bs-example-modal-lg">Filtrar</button>


                   <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog modal-lg">

                      <div class="modal-content">
                        <br>
                        <br>
                        <br>
                        <form  action="" method="POST">
                        {% csrf_token %}

                      <div class="field item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">Titulo</label>
                        <div class="col-md-9 col-sm-9 ">
                          <input type="text" class="form-control" name="titulo">
                        </div>
                      </div>
                      <div class="field item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">clasificacion</label>
                        <div class="col-md-9 col-sm-9 ">
                          <select class="form-control" name="clasificacion">
                            <option value="No Especificado">No especificado</option>
                            <option value="Territorial">Territorial</option>
                            <option value="Nacional">Nacional</option>
                          </select>
                        </div>
                      </div>
                      <div class="field item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">Estado</label>
                        <div class="col-md-9 col-sm-9 ">
                          <select class="form-control" name="estado">
                            <option value="No Especificado">No especificado</option>
                            <option value="Nuevo">Nuevo</option>
                            <option value="Pendiente">Pendiente</option>
                            <option value="Solucionado">Solucionado</option>

                          </select>
                        </div>
                      </div>
                      <div class="field item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">Unidad Dirigida</label>
                        <div class="col-md-9 col-sm-9 ">
                          <select class="form-control" name="unidad_id">
                          <option value="No Especificado">No especificado</option>
                            {% for unidad in unidades %}
                                <option value="{{ unidad.id }}">{{ unidad }}</option>
                            {% endfor %}

                          </select>
                        </div>
                      </div>
                      <div class="field item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">Sección Sindical</label>
                        <div class="col-md-9 col-sm-9 ">
                          <select class="form-control" name="seccion_sindical_id">
                          <option value="No Especificado">No especificado</option>
                            {% for seccion in secciones %}
                                <option value="{{ seccion.id }}">{{ seccion }}</option>
                            {% endfor %}

                          </select>
                        </div>
                      </div>
                      <div class="field item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align ">Proceso</label>
                        <div class="col-md-6 col-sm-6 ">
                          <select class="form-control" name="proceso">
                          <option value="No especificado">No especificado</option>
                            {% for proceso in procesos %}
                                <option value="{{ proceso.id }}">{{ proceso }}</option>
                            {% endfor %}

                          </select>
                        </div>
                      </div>


                      <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Fecha de Creación</label>
                      <div class="col-md-6 col-sm-6">
                        <input class="form-control" type="date" name="fecha" value=""></div>
                    </div>
                    <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Fecha de Vencimiento</label>
                      <div class="col-md-6 col-sm-6">
                        <input class="form-control" type="date" name="fecha_vencida" value="No espcificado"></div>
                    </div>
                      <div class="ln_solid"></div>
                      <div class="form-group row">
                        <div class="col-md-9 col-sm-9  offset-md-3">
                          <button type="submit" class="btn btn-success">Filtrar</button>
                        </div>
                      </div>

                    </form>

                      </div>
                    </div>
                  </div>
                     &nbsp;
                     {% if request.user|secretario %}
                      <a href="{% url 'planteamientos:crear_planteamiento' %}" type="button" class="btn btn-secondary btn-sm " >Adicionar Planteamiento</a>
                      {% endif %}
                  </div>
                    <div class="clearfix"></div>

                  </div>
                  <div class="x_content">
                      <div class="row">
                          <div class="col-sm-12">
                          {% include 'mensajes.html' %}
                            <div class="card-box table-responsive">

                        <div id="datatable-buttons_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap no-footer">

                        <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline" style="width: 100%;" role="grid" aria-describedby="datatable-buttons_info">
                      <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 40px;" aria-sort="ascending" aria-label="Name: activate to sort column descending">
                                Indice
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 132px;" aria-label="Position: activate to sort column ascending">
                                Título
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 132px;" aria-label="Position: activate to sort column ascending">
                                Clasificación
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 57px;" aria-label="Office: activate to sort column ascending">
                                Estado
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 57px;" aria-label="Office: activate to sort column ascending">
                                Unidad Dirigida
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 80px;" aria-label="Age: activate to sort column ascending">
                                Sección Sindical
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 48px;" aria-label="Salary: activate to sort column ascending">
                                Secretario
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 50px;" aria-label="Start date: activate to sort column ascending">
                                Proceso
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 50px;" aria-label="Start date: activate to sort column ascending">
                                Fecha de Creación
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" style="width: 50px;" aria-label="Start date: activate to sort column ascending">
                                Fecha de Vencimiento
                            </th>

                        </tr>
                      </thead>
                            <tbody>

                      <!-------------------- Tabla de Planteamientos ----------------------->

                      {% for planteamiento in planteamientos %}

                      <tr role="row" class="odd">

                          <td tabindex="0" class="sorting_1">{{ forloop.counter }}</td>
                          <td><a href="{% url 'planteamientos:inbox' planteamiento.id %}" >{{ planteamiento.titulo }}</a></td>
                          <td>{{ planteamiento.clasificacion }}</td>
                          <td>{{ planteamiento.estado }}</td>
                          <td>{{ planteamiento.unidad }}</td>
                          <td>{{ planteamiento.seccion_sindical.nombre }}</td>
                          <td>{{ planteamiento.secretario }}</td>
                          <td>{{ planteamiento.procesos| ninguno }}</td>
                          <td>{{ planteamiento.fecha }}</td>
                          <td>{{ planteamiento.fecha_vencida }}</td>

                        </tr>

                        {% endfor %}

                      <!-------------------------  / Tabla de Planteamientos -------------------------->
                      </tbody>
                    </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
    </div>
  </div>
</div>
    </div>







{% endblock %}

{% block script %}




    <!-- iCheck -->
    <script src="{% static "scp/vendors/iCheck/icheck.min.js" %}"></script>

    <!-- DataTables -->
    <script src="{% static "scp/vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-buttons/js/buttons.flash.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-buttons/js/buttons.print.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js" %}"></script>
    <script src="{% static "scp/vendors/datatables.net-scroller/js/dataTables.scroller.min.js" %}"></script>

   <script>

        let import_parent = document.getElementsByClassName("dt-buttons btn-group")[0]

        let a = document.createElement("a")
        a.href = {% url "planteamientos:xlsx" %}
        a.innerText = "Excel"
        import_parent.appendChild(a)

    </script>

{% endblock %}