apps/planteamientos/urls.py
from django.urls import path
from . import views

app_name = 'planteamientos'
urlpatterns = [

    path('mostrar/<int:todos>', views.planteamiento, name='planteamiento'),
    path('inbox/<int:planteamiento_id>/', views.inbox, name='inbox'),
    path('crear/', views.crear_planteamiento, name='crear_planteamiento'),
    path('notificaciones/', views.notificaciones, name='notificaciones'),
    path('editar/<id_planteamiento>/', views.editar_planteamiento, name='editar'),
    path("import/xlsx/", views.PlanteamientosImportXLSXService.as_view(),
         name="xlsx"),
    path("evaluacion/<int:planteamiento_id>/<int:aprobado>", views.PlanteamientosAprobar.as_view(), name="evaluar_planteamiento")
]

apps/usuarios/urls.py
from django.urls import path
from . import users

app_name = 'usuarios'
urlpatterns = [

    path('mostrar', users.mostrar_usuarios, name='mostrar_usuarios'),
    path('registrar', users.registrar_usuario, name='registrar_usuario'),
    path('eliminar/<int:id_usuario>/', users.eliminar_usuario, name='eliminar_usuario'),
    path('editar/<int:id_usuario>/<int:roll>/', users.editar_usuario, name='editar_usuario'),
    path('perfil/', users.profile, name='perfil'),
    path('cambiarcontraseña/', users.cambio_password, name='cambio_password'),
    path('ayuda/', users.ayuda, name='ayuda'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.mixin import login, errors
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import cache_control
from django.conf import settings

handler404 = errors.handler_404
handler500 = errors.handler_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('planteamientos/', include('apps.planteamientos.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('unidades/', include('apps.respuestas.urls')),
    path('unidades/', include('apps.unidades.urls')),
    path('', login.login, name='login'),
    path('logout', login.logout, name='logout'),
    path('olvidado/', login.olvidar_contrasegna, name='olvidar')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

templates/usuarios/cambio_password.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

          <!-- page content -->
      <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Editar Usuario</h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12">
            {% include 'mensajes.html' %}
              <div class="x_panel">
                <div class="x_content">
                  <form class="" action="" method="POST" novalidate>
                    {% csrf_token %}
                    <span class="section">Cambio de Contraseña {% if usuario.first_name %} de {{ usuario.first_name }} {% endif %}</span>
                      <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Contraseña Nueva</label>
                      <div class="col-md-6 col-sm-6">

                          <input class="form-control" data-validate-length-range="6" data-validate-words="2" name="password"
                           required="required"  type="password" />
                      </div>
                    </div>
                      <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Repetir Contraseña</label>
                      <div class="col-md-6 col-sm-6">
                          <input class="form-control" data-validate-length-range="6" data-validate-words="2" name="password2"
                           required="required" type="password" />
                      </div>

                    </div>


                      <br>

                      <br>
                      <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                    <button type='submit' class="btn btn-primary" name="id" value="{{ user.id }}">Editar</button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->


{% endblock %}

{% block content %}




{% endblock %}

templates/usuarios/editar_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

          <!-- page content -->
      <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Editar Usuario</h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12">

            {% include 'mensajes.html' %}
              <div class="x_panel">
                <div class="x_content">
                  <form class="" action="" method="POST" novalidate>
                    {% csrf_token %}
                    <span class="section">Informacion Personal {% if usuario.first_name %} de {{ usuario.first_name }} {% endif %}</span>
                      <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Nombre<span
                          class="required">*</span></label>
                      <div class="col-md-6 col-sm-6">

                          <input class="form-control" data-validate-length-range="6" data-validate-words="2" name="first_name"
                           required="required"  value="{{ usuario.first_name }}" />
                      </div>
                    </div>
                      <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Apellidos<span
                          class="required">*</span></label>
                      <div class="col-md-6 col-sm-6">
                          <input class="form-control" data-validate-length-range="6" data-validate-words="2" name="last_name"
                           required="required" value="{{ usuario.last_name }}" />
                      </div>
                    </div>
                    <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Nombre de Usario<span
                          class="required">*</span></label>
                      <div class="col-md-6 col-sm-6">

                        <input class="form-control" data-validate-length-range="6" data-validate-words="2" name="username"
                           required="required" value="{{ usuario.username }}" />
                      </div>
                    </div>
                    <div class="field item form-group">
                      <label class="col-form-label col-md-3 col-sm-3  label-align">Correo Electronico<span
                          class="required">*</span></label>
                      <div class="col-md-6 col-sm-6">
                          <input class="form-control" name="email" class='email' required="required" type="email"
                          value="{{ usuario.email}}" />
                       </div>
                    </div>
                  {% if roll == 1 %}
                    <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" value="Administrador" name="admin" {% if usuario.is_staff %} checked {% endif %}> &nbsp; Supervisor ?
                            </label>
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" value="SuperUsuario" name="superuser"  {% if usuario.is_superuser %} checked {% endif %}> &nbsp; Administrador ?
                            </label>
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" value="Activado" name="activo" {% if usuario.is_active %} checked {% endif %}> &nbsp; Activo ?
                            </label>
                          </div>
                        </div>
                    </div>
                  {% else %}
                      <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                        <div class="checkbox">
                            <label>
                               &nbsp;<a href="{% url 'usuarios:cambio_password' %}"> Desea Cambiar la contraseña ?</a>
                            </label>
                          </div>
                        </div>
                    </div>
                      <input type="hidden" name="activo" value="True">
                      {% if user.is_staff %}
                          <input type="hidden" name="admin" value="True">
                       {% endif %}

                  {% endif %}
                      <br>
                      <br>
                      <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                    <button type='submit' class="btn btn-primary">Editar</button>
                        </div>
                      </div>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->


{% endblock %}

{% block content %}




{% endblock %}

templates/usuarios/mostrar_usuarios.html
{% extends 'base.html' %}
{% load static %}
{% load planteamientos_tags %}

{% block link %}

    <!-- iCheck -->
   <link href="{% static "scp/vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">

{% endblock %}



{% block body %}

        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Tabla <small>con el contenido de todos los usuarios</small></h3>
              </div>
              <form action="" method="GET" >
              <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                  <div class="input-group">

                    <input name="buscar" type="text" class="form-control" placeholder="usuarios ...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="submit">Buscar</button>
                    </span>
                  </div>
                </div>
              </div>
              </form>
            </div>

            <div class="clearfix"></div>

            <div class="row" style="display: block;">


              <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12  ">
              {% include 'mensajes.html' %}
                <div class="x_panel">
                  <div class="x_title d-flex">
                    <h2>Listado de Usuarios </h2>
                    <a href="{% url 'usuarios:registrar_usuario' %}" type="button" class="btn btn-secondary btn-sm ml-auto" >Adicionar Usuario</a>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">

                        <thead>
                          <tr class="headings">
                            <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                            <th class="column-title">Nombre de Usuario</th>
                            <th class="column-title">Correo Electrónico</th>
                            <th class="column-title">Nombre </th>
                            <th class="column-title">Apellidos</th>
                            <th class="column-title">Administrador </th>
                            <th class="column-title no-link last"><span class="nobr">Acción</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Eliminar ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>

                        <tbody>
                        {% for user in users %}
                          <tr class="even pointer">
                            <td class="a-center ">
                              <input type="checkbox" class="flat" name="table_records">
                            </td>
                            <td class=" ">{{ user.username }}</td>
                            <td class=" ">{{ user.email }}</td>
                            <td class=" ">{{ user.first_name }}</td>
                            <td class=" ">{{ user.last_name}}</td>
                            <td class=" ">
                                {% if user.is_staff %}
                                    <i class="fa fa-check" ></i>
                                {% endif %}

                            </td>
                            <td class=" last"><a type="button"  data-toggle="modal" data-target=".bs-example-modal-{{ user.id }}">Ver</a>
                            </td>
                          </tr>

                            <!------------------------- Large modal ------------------------->


                            <div class="modal fade bs-example-modal-{{ user.id }}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                                <div class="modal-dialog modal-lg">
                                <div class="modal-content">

                                <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabel">Ver usuario {{ user.get_full_name }}</h4>
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                                    </button>
                                </div>
                                <div class="modal-body">

                                    <p><strong>Nombre de usuario:</strong> {{ user.username }}</p>
                                    <p><strong>Correo:</strong> {{ user.email }}</p>
                                    <p><strong>Supervisor:</strong>
                                        {{ user.is_staff| Si_o_No }}
                                    </p>
                                    <p><strong>Administrador:</strong>
                                        {{ user.is_superuser| Si_o_No }}
                                    </p>
                                    <p><strong>Activo:</strong>
                                        {{ user.is_active| Si_o_No }}
                                    </p>
                                    <p><strong>Ultima Sesion:</strong>{{ user.last_login }}</p>
                                    <p><strong>Fecha de Autenticación:</strong> {{ user.date_joined }}</p>

                                </div>
                                <div class="modal-footer d-flex">
                                    <a type="button" class="btn btn-danger mr-auto" href="{% url 'usuarios:eliminar_usuario' user.id %}" >Eliminar</a>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <a type="button" class="btn btn-primary" href="{% url 'usuarios:editar_usuario' user.id 1 %}">Editar</a>
                                </div>
                                </div>
                                </div>
                                </div>
                            <!---------------------- /modals ------------------------------->
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>


                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


{% endblock %}

{% block script %}

    <!-- iCheck -->
    <script src="{% static "scp/vendors/iCheck/icheck.min.js" %}"></script>

{% endblock %}

templates/usuarios/perfil.html
{% extends 'base.html' %}
{% load static %}
{% load planteamientos_tags %}

{% block body %}

    <div class="right_col" role="main" style="min-height: 1145px;">
          <div class="">


            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 ">
              {% include 'mensajes.html' %}
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Perfil <small>Reporte de Actividades</small></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="col-md-3 col-sm-3  profile_left">
                      <div class="profile_img">
                        <div id="crop-avatar">
                          <!-- Current avatar -->
                          <img class="img-responsive avatar-view" alt="Avatar" title="Change the avatar" src="{% static 'scp/production/images/user.png' %}">
                        </div>
                      </div>
                      <h3>{{ perfil.user.get_full_name }}</h3>

                      <ul class="list-unstyled user_data">
                        <li><i class="fa fa-map-marker user-profile-icon"></i>
                            {{ perfil.vinculo.unidad }}
                        </li>

                        <li>
                          <i class="fa fa-briefcase user-profile-icon"></i> {{ perfil.vinculo.vinculo }}
                        </li>

                        <li class="m-top-xs">
                          <i class="fa fa-send user-profile-icon"></i>
                          {{ user.email }}
                        </li>
                      </ul>

                      <a class="btn btn-success" href="{% url 'usuarios:editar_usuario' user.id 0 %}" ><i class="fa fa-edit m-right-xs"></i>Editar Perfil</a>
                      <br>
                      <br>
                      <br>
                      <!-- start skills -->
                      <h4> Estado de los Planteamientos </h4>
                      <ul class="list-unstyled user_data">
                        <li>
                          <p>Nuevos</p>
                          <div class="progress progress_sm">
                            <div class="progress-bar bg-blue" role="progressbar" data-transitiongoal="50" aria-valuenow="49" style="width: {{ estado.Nuevo }}%;"></div>
                          </div>
                        </li>
                        <li>
                          <p>Pendientes</p>
                          <div class="progress progress_sm">
                            <div class="progress-bar bg-orange" role="progressbar" data-transitiongoal="70" aria-valuenow="69" style="width: {{estado.Pendiente}}%;"></div>
                          </div>
                        </li>
                        <li>
                          <p>Solucionado</p>
                          <div class="progress progress_sm">
                            <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="30" aria-valuenow="29" style="width: {{ estado.Solucionado }}%;"></div>
                          </div>
                        </li>
                      </ul>
                      <!-- end of skills -->

                    </div>
                    <div class="col-md-9 col-sm-9 ">



                      <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                          <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Planteamientos Recientes</a>
                          </li>
                          <li role="presentation" class="active"><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="true">Perfil</a>
                          </li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                          <div role="tabpanel" class="tab-pane active " id="tab_content1" aria-labelledby="home-tab">

                            <!-- start recent activity -->
                            <ul class="messages">

                              {% if ninguno  %}
                            {% for planteamiento in planteamientos %}
                              <li>
                                <img src="{% static 'scp/production/images/user.png' %}" class="avatar" alt="Avatar">
                                <div class="message_date">
                                  <h3 class="date text-info">{{ planteamiento.fecha.day }}</h3>
                                  <p class="month">{{ planteamiento.fecha|date:" M "}}</p>
                                </div>
                                <div class="message_wrapper">
                                  <h4 class="heading">{{ planteamiento.titulo }} &nbsp; &nbsp; &nbsp; <small >{{ planteamiento.estado }}</small></h4>
                                  <blockquote class="message">{{ planteamiento.abreviar }}</blockquote>
                                  <br>
                                  <p class="url">
                                    <span class="fs1 text-info" aria-hidden="true" data-icon=""></span>
                                    <a href="{% url 'planteamientos:inbox' planteamiento.id %}"><i class="fa fa-paperclip"></i> ver detalles </a>
                                      {% if perfil.tiene_seccion or perfil.tiene_unidad %}
                                          {% if perfil.tiene_seccion %}
                                          para: {{ planteamiento.unidad }}
                                          {% endif %}
                                          {% if perfil.tiene_unidad %}
                                                de: {{ planteamiento.seccion_sindical }}
                                          {% endif %}
                                      {% else %}
                                          de: {{ planteamiento.seccion_sindical }} para: {{ planteamiento.unidad }}
                                      {% endif %}
                                {% endfor %}

                                  </p>
                                </div>
                              </li>
                                {% else %}
                                  <li>
                                <img src="{% static 'scp/production/images/user.png' %}" class="avatar" alt="Avatar">
                                <div class="message_date">
                                  <h3 class="date text-info">{{ planteamiento.fecha.day }}</h3>
                                  <p class="month">{{ planteamiento.fecha|date:" M "}}</p>
                                </div>
                                <div class="message_wrapper">
                                  <h4 class="heading">{{ planteamiento.titulo }}</h4>
                                  <blockquote class="message">{{ planteamiento.abreviar }}</blockquote>
                                  <br>
                                  <p class="url">
                                    <span class="fs1 text-info" aria-hidden="true" data-icon=""></span>
                                  <i class="fa fa-plus"></i>
                                  No se han encontrado planteamientos recientes relacionado a este perfil...
                                  {% if perfil.tiene_seccion %}
                                    <a href="{% url 'planteamientos:crear_planteamiento' %}">


                                          si desea realizar algun planteamiento presione en este link
                                    </a>
                                   {% endif %}
                                  </p>
                                </div>
                              </li>



                                {% endif %}

                            </ul>
                            <!-- end recent activity -->

                          </div>
                          <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">



                          </div>
                          <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                              <ul>
                                <li>
                                    <strong>nombre de usuario: </strong> &nbsp; {{ user.username }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Nombre: </strong> &nbsp; {{ user.get_full_name }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Correo: </strong> &nbsp; {{ user.email }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Supervisor: </strong> &nbsp; {{ user.is_staff|Si_o_No }}
                                </li>
                                  <li>
                                    <strong>Administrador: </strong> &nbsp; {{ user.is_superuser|Si_o_No }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Secretario: </strong> &nbsp; {{ perfil.tiene_seccion|Si_o_No }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Representante: </strong> &nbsp; {{ perfil.tiene_unidad|Si_o_No }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Último inicio de Sesión: </strong> &nbsp; {{ user.last_login }}
                                </li>
                                  <br>
                                  <li>
                                    <strong>Fecha de autenticación: </strong> &nbsp; {{ user.date_joined }}
                                </li>

                              </ul>

                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

{% endblock %}