apps/unidades/urls.py
from django.urls import path
from . import views

app_name = 'unidades'
urlpatterns = [

    path('listar/', views.listar, name='listar'),
    path('editar/', views.editar, name='editar'),
    path('eliminar/<int:unidad_id>/', views.eliminar, name='eliminar'),
    path('listar_seccion/', views.listar_seccion, name='listar_seccion'),
    path('editar_seccion/', views.editar_seccion, name='editar_seccion'),
    path('eliminar_seccion/<int:seccion_id>/', views.eliminar_seccion, name='eliminar_seccion')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.mixin import login, errors
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import cache_control
from django.conf import settings

handler404 = errors.handler_404
handler500 = errors.handler_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('planteamientos/', include('apps.planteamientos.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('unidades/', include('apps.respuestas.urls')),
    path('unidades/', include('apps.unidades.urls')),
    path('', login.login, name='login'),
    path('logout', login.logout, name='logout'),
    path('olvidado/', login.olvidar_contrasegna, name='olvidar')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

apps/unidades/models.py
from django.db import models
from django.contrib.auth.models import User


class UnidadOrganizativa(models.Model):
    """
     model Unidad Organizativas; \n
     your instance gets: \n
        *  nombre -- Oranizational Unit name \n
        *  responsable -- responsible user for the Organizational Unit

    """

    nombre = models.CharField(max_length=60, unique=True)
    responsable = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.nombre

    def delete(self, **kwargs):
        from apps.planteamientos.models import Planteamiento
        planteamientos = Planteamiento.objects.filter(unidad_id=self.id)
        for i in planteamientos:
            i.unidad_id = 'unidad'
            i.save()
        super(UnidadOrganizativa, self).delete(**kwargs)




class SeccionSindical(models.Model):
    """
     model SeccionSindical; \n
     your instance gets: \n
        * nombre -- Seccion Sindical name \n
        * secretario -- name of secretary \n
        * unidad -- relationship with the unit

    """

    nombre = models.CharField(max_length=60, unique=True)
    secretario = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    unidad = models.ForeignKey(UnidadOrganizativa, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.nombre

apps/unidades/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from apps.mixin.forms import *
from django.shortcuts import get_object_or_404
from django.contrib import messages


# --------------------------  funciones del modulo unidad organizativa  ---------------------------- #


def listar(request):
    unidades = UnidadOrganizativa.objects.all()
    form = FormUnidad()
    if request.method == "GET":
        x = request.GET.get('buscar', '')
        unidades = unidades.filter(Q(responsable__first_name__icontains=x) | Q(nombre__icontains=x))
    elif request.method == "POST":
        form = FormUnidad(data=request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            msj = '{} se le ha asignado la unidad {}'.format(f.responsable.get_full_name(), f.nombre)
            messages.success(request, msj, 'ÉXITOS !! ')
            f.save()
        else:
            msj = 'Usted ha cometido un error en los campos, '
            messages.error(request, msj.join(i + ', ' for i in form.errors))

    return render(request, 'unidades/unidad_organizativa.html', locals())


def editar(request):
    if request.method == "POST":
        unidad = get_object_or_404(UnidadOrganizativa, id=request.POST["Editar"])
        unidad.nombre = request.POST["nombre"]
        unidad.responsable_id = int(request.POST["responsable"])
        unidad.save()
        messages.success(request, 'Se ha editado la unidad %s satisfactoriamente' % unidad.nombre, 'ÉXITOS !!')
    return redirect("unidades:listar")


def eliminar(request, unidad_id):
    unidad = UnidadOrganizativa.objects.get(id=unidad_id)
    p = Planteamiento.objects.filter(unidad=unidad).count()
    unidad.delete()
    messages.success(request, 'Se ha eliminado la unidad %s' % unidad.nombre, 'ÉXITOS !!')
    if p > 0: messages.warning(request,
                               '{} planteamientos ya no guardan relación con la Unidad Organizativa eliminada'.format(p),
                               'ADVERTENCIA !! ')
    return redirect('unidades:listar')


# --------------------------  funciones del modulo seccion sindical  ---------------------------- #


def listar_seccion(request):
    secciones = SeccionSindical.objects.all()
    form = FormSeccion()
    if request.method == "GET":
        x = request.GET.get('buscar', '')
        secciones = secciones.filter(Q(secretario__first_name__icontains=x) | Q(nombre__icontains=x))
    elif request.method == "POST":
        form = FormSeccion(data=request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            msj = '{} se le ha asignado la sección {}'.format(f.secretario.get_full_name(), f.nombre)
            messages.success(request, msj, 'ÉXITOS !! ')
            f.save()
        else:
            msj = 'Usted ha cometido un error en los campos, '
            messages.error(request, msj.join(i + ', ' for i in form.errors))

    return render(request, 'unidades/seccion_sindical.html', locals())


def editar_seccion(request):
    if request.method == "POST":
        seccion = get_object_or_404(SeccionSindical, id=request.POST["Editar"])
        seccion.nombre = request.POST["nombre"]
        seccion.secretario_id = int(request.POST["secretario"])
        seccion.unidad_id = int(request.POST["unidad"])
        seccion.save()
        messages.success(request, 'Se ha ediado la unidad %s satisfactoriamente' % seccion.nombre, 'ÉXITOS !!')
    return redirect("unidades:listar_seccion")


def eliminar_seccion(request, seccion_id):
    seccion = SeccionSindical.objects.get(id=seccion_id)
    p = Planteamiento.objects.filter(seccion_sindical=seccion).count()
    seccion.delete()
    messages.success(request, 'Se ha eliminado la sección %s' % seccion.nombre, 'EXITOS !!')
    if p > 0: messages.warning(request,
                               '{} planteamientos ya no guardan relación con la Sección Sindical eliminada'.format(p),
                               'ADVERTENCIA !! ')
    return redirect("unidades:listar_seccion")

templates/unidades/listar.html
{% extends 'base.html' %}
{% load static %}
{% load unidades_tags %}

{% block link %}

    <!-- iCheck -->
   <link href="{% static "scp/vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">

{% endblock %}

{% block body %}

     <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Tabla <small>con contenido de todas las unidades</small></h3>
              </div>
                <form action="" method="GET">
              <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                  <div class="input-group">

                        <input type="text" class="form-control" placeholder="..." name="buscar">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Buscar</button>
                        </span>

                  </div>
                </div>
              </div>
            </div>
            </form>
              <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                  <div class="x_title d-flex">
                    <h2>Unidades Organizativas</h2>

                      <!-------------------- Adicionar Unidad  -------------------------------------------->
                      <button type="button" class="btn btn-secondary ml-auto" data-toggle="modal" data-placement="top" title="" data-original-title="Tooltip bottom" data-target=".bs-example-modal-sm">Adicionar Unidad</button>
                                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <form action="" method = "POST">
                                            {% csrf_token %}
                                        <div class="modal-body">
                                            <h4>Adicionar Unidad</h4>

                                            <div class="form-group row">
                                                <label class="control-label col-md-4 col-sm-4 ">Unidad</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        {{ form.nombre }}
                                                    </div>
                                                <br>
                                                <br>
                                                <br>
                                                <label class="control-label col-md-4 col-sm-4 ">Responsable</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        {{ form.responsable }}
                                                    </div>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Adicionar</button>
                                        </div>
                                        </form>
                                    </div>
                                </div>
                                </div>

                      <!-------------------- Adicionar Unidad  -------------------------------------------->

                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">
                      <table class="table table-striped jambo_table bulk_action">
                          <thead>
                          <tr class="headings">
                              <th>
                                  <input type="checkbox" id="check-all" class="flat">
                              </th>
                              <th class="column-title">Índice </th>
                              <th class="column-title">Unidad </th>
                              <th class="column-title">Responsable </th>
                              <th class="column-title">Acción</th>
                          </tr>
                          </thead>
                          <tbody>

                          <!---------------------------------------------------------->
                          {% for unidad in unidades %}
                              <tr class="even pointer">
                                  <td class="a-center ">
                                      <input type="checkbox" class="flat" name="table_records">
                                  </td>
                                  <td class=" ">{{ forloop.counter }}</td>
                                  <td class=" ">{{ unidad.nombre }} </td>
                                  <td class=" ">{{ unidad.responsable }}</td>
                                  <td class=" last"><a type="button"  data-toggle="modal" data-target=".bs-example-modal-{{ unidad.id }}">Ver</a></td>
                              </tr>


                              <!------------------------- Large modal ------------------------->


                              <div class="modal fade bs-example-modal-{{ unidad.id }}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                                  <div class="modal-dialog modal-lg">
                                      <div class="modal-content">

                                          <div class="modal-header">
                                              <h4 class="modal-title" id="myModalLabel">Ver unidad</h4>
                                              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                                              </button>
                                          </div>
                                          <form action="{% url 'unidades:editar' %}" method="POST">
                                              {% csrf_token %}
                                              <div class="modal-body">
                                                  <div class="form-group row">
                                                      <label class="control-label col-md-3 col-sm-3 ">Unidad</label>
                                                      <div class="col-md-9 col-sm-9 ">
                                                          <input type="text" name="nombre" id="autocomplete-custom-append" class="form-control " autocomplete="off" value="{{ unidad.nombre }}">
                                                      </div>
                                                  </div>
                                                  <br>
                                                  <div class="form-group row">
                                                      <label class="control-label col-md-3 col-sm-3 ">Responsable</label>
                                                      <div class="col-md-9 col-sm-9 ">
                                                          <select class="form-control" name="responsable">
                                                              {% for option in usuarios|sum_list:unidad.responsable %}
                                                                  <option value="{{ option.id }}" {% if unidad.responsable == option %}selected{% endif %}>{{ option.username}}</option>
                                                              {% endfor %}
                                                          </select>
                                                      </div>
                                                  </div>

                                              </div>
                                              <div class="modal-footer d-flex">
                                                  <a type="button" class="btn btn-danger mr-auto" href="{% url 'unidades:eliminar' unidad.id %}" >Eliminar</a>
                                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                  <button type="submit" class="btn btn-primary" name="Editar" value="{{ unidad.id }}" >Editar</button>
                                              </div>
                                          </form>
                                  </div>
                              </div>
                              <!---------------------- /modals ------------------------------->

                        {% endfor %}
                        <!------------------------------------------------------------->
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->


{% endblock %}

{% block script %}

    <!-- iCheck -->
    <script src="{% static "scp/vendors/iCheck/icheck.min.js" %}"></script>

{% endblock %}

templates/unidades/seccion_sindical.html
{% extends 'base.html' %}
{% load static %}
{% load unidades_tags %}

{% block link %}

    <!-- iCheck -->
   <link href="{% static "scp/vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">

{% endblock %}

{% block body %}

     <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Tabla <small>con contenido de todas las secciones sindicales</small></h3>
              </div>
                <form action="" method="GET">
              <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                  <div class="input-group">

                        <input type="text" class="form-control" placeholder="..." name="buscar">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Buscar</button>
                        </span>

                  </div>
                </div>
              </div>


            </form>
              <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12  ">
              {% include 'mensajes.html' %}
                <div class="x_panel">
                  <div class="x_title d-flex">
                    <h2>Secciones Sindicales</h2>

                      <!-------------------- Adicionar Seccion Sindical  -------------------------------------------->
                      <button type="button" class="btn btn-secondary ml-auto" data-toggle="modal" data-placement="top" title="" data-original-title="Tooltip bottom" data-target=".bs-example-modal-sm">Adicionar Sección Sindical</button>
                                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <form action="" method = "POST">
                                            {% csrf_token %}
                                        <div class="modal-body">
                                            <h4>Adicionar Sección Sindical</h4>

                                            <div class="form-group row">
                                                <label class="control-label col-md-4 col-sm-4 ">Sección Sindical</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        {{ form.nombre }}
                                                    </div>
                                                <br>
                                                <br>
                                                <br>
                                                <label class="control-label col-md-4 col-sm-4 ">Secretario</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        {{ form.secretario }}
                                                    </div>
                                                <br>
                                                <br>
                                                <br>
                                                <label class="control-label col-md-4 col-sm-4 ">Unidad</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        {{ form.unidad }}
                                                    </div>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Adicionar</button>
                                        </div>
                                        </form>
                                    </div>
                                </div>
                                </div>

                      <!-------------------- Adicionar Seccion Sindical  -------------------------------------------->

                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">
                      <table class="table table-striped jambo_table bulk_action">
                          <thead>
                          <tr class="headings">
                              <th class="column-title">Índice </th>
                              <th class="column-title">Sección Sindical </th>
                              <th class="column-title">Secretario </th>
                              <th class="column-title">Unidad Organizativa </th>
                              <th class="column-title">Acción</th>
                          </tr>
                          </thead>
                          <tbody>

                          <!---------------------------------------------------------->
                          {% for seccion in secciones %}
                              <tr class="even pointer">
                                  <td class=" ">{{ forloop.counter }}</td>
                                  <td class=" ">{{ seccion.nombre }} </td>
                                  <td class=" ">{{ seccion.secretario }}</td>
                                  <td class=" ">{{ seccion.unidad }}</td>
                                  <td class=" last"><a type="button"  data-toggle="modal" data-target=".bs-example-modal-{{ seccion.id }}">Ver</a></td>
                              </tr>


                              <!------------------------- Large modal ------------------------->


                              <div class="modal fade bs-example-modal-{{ seccion.id }}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                                  <div class="modal-dialog modal-lg">
                                      <div class="modal-content">

                                          <div class="modal-header">
                                              <h4 class="modal-title" id="myModalLabel">Ver sección sindical</h4>
                                              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                                              </button>
                                          </div>
                                          <form action="{% url 'unidades:editar_seccion' %}" method="POST">
                                              {% csrf_token %}
                                              <div class="modal-body">
                                                  <div class="form-group row">
                                                      <label class="control-label col-md-3 col-sm-3 ">Sección Sindical</label>
                                                      <div class="col-md-9 col-sm-9 ">
                                                          <input type="text" name="nombre" id="autocomplete-custom-append" class="form-control " autocomplete="off" value="{{ seccion.nombre }}">
                                                      </div>
                                                  </div>
                                                  <br>
                                                  <div class="form-group row">
                                                      <label class="control-label col-md-3 col-sm-3 ">Secretario</label>
                                                      <div class="col-md-9 col-sm-9 ">
                                                          <select class="form-control" name="secretario">
                                                              {% for option in form.get_usuarios|sum_list:seccion.secretario %}
                                                                  <option value="{{ option.id }}" {% if seccion.secretario == option %}selected{% endif %}>{{ option.username}}</option>
                                                              {% endfor %}
                                                          </select>
                                                      </div>
                                                  </div>
                                                  <br>
                                                  <div class="form-group row">
                                                      <label class="control-label col-md-3 col-sm-3 ">Unidad</label>
                                                      <div class="col-md-9 col-sm-9 ">
                                                          <select class="form-control" name="unidad">
                                                              {% for option in form.unidades %}
                                                                  <option value="{{ option.id }}" {% if seccion.unidad_id == option.id %}selected{% endif %}>{{ option.nombre}}</option>
                                                              {% endfor %}
                                                          </select>
                                                      </div>
                                                  </div>

                                              </div>
                                              <div class="modal-footer d-flex">
                                                  <a type="button" class="btn btn-danger mr-auto" href="{% url 'unidades:eliminar_seccion' seccion.id %}" >Eliminar</a>
                                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                  <button type="submit" class="btn btn-primary" name="Editar" value="{{ seccion.id }}" >Editar</button>
                                              </div>
                                          </form>
                                  </div>
                              </div>
                              <!---------------------- /modals ------------------------------->

                        {% endfor %}
                        <!------------------------------------------------------------->
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->



{% endblock %}

{% block script %}


    <!-- iCheck -->
    <script src="{% static "scp/vendors/iCheck/icheck.min.js" %}"></script>

{% endblock %}